include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/generated/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore

linter:
  rules:
    use_build_context_synchronously: false      # This causes false-positives with riverpod
    library_private_types_in_public_api: false  # This causes false-positives with riverpod
    require_trailing_commas: true
    avoid_slow_async_io: true
    unnecessary_lambdas: true
    sort_constructors_first: true
    unnecessary_to_list_in_spreads: true
    use_string_buffers: true
    use_decorated_box: true
    use_colored_box: true